#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

export DEBIAN_FRONTEND=noninteractive

cd /tmp
add-apt-repository cloud-archive:liberty -y
apt-get update -y && apt-get install -y python-nova nova-common neutron-common linux-headers-3.13.0-116-generic
